# Generated by Django 5.2.8 on 2026-03-15 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_rename_k_prediction_k_rename_p_prediction_p_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('phone_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('country', models.CharField(choices=[('india', 'India'), ('bangladesh', 'Bangladesh'), ('pakistan', 'Pakistan'), ('nepal', 'Nepal'), ('sri_lanka', 'Sri Lanka'), ('myanmar', 'Myanmar'), ('thailand', 'Thailand'), ('vietnam', 'Vietnam'), ('indonesia', 'Indonesia'), ('philippines', 'Philippines'), ('malaysia', 'Malaysia'), ('china', 'China'), ('japan', 'Japan'), ('south_korea', 'South Korea')], max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pm_kisan_registered', models.BooleanField(default=False)),
                ('pm_kisan_id', models.CharField(blank=True, max_length=20, null=True)),
                ('current_crops', models.JSONField(blank=True, default=list)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_unit', models.CharField(default='acres', max_length=20)),
                ('help_needed', models.JSONField(blank=True, default=list)),
                ('help_description', models.TextField(blank=True, null=True)),
                ('govt_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('village', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
